import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                heading: ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                surface: '#18120e',
                'surface-dim': '#18120e',
                'surface-bright': '#3f3833',
                'surface-container-lowest': '#130d09',
                'surface-container-low': '#211a16',
                'surface-container': '#251e1a',
                'surface-container-high': '#302924',
                'surface-container-highest': '#3b332f',
                'on-surface': '#ede0d9',
                'on-surface-variant': '#d9c2b1',
                'inverse-surface': '#ede0d9',
                'inverse-on-surface': '#362f2a',
                outline: '#a18d7d',
                'outline-variant': '#544436',
                'surface-tint': '#ffb876',
                primary: '#ffb876',
                'on-primary': '#4b2800',
                'primary-container': '#d98324',
                'on-primary-container': '#4a2700',
                'inverse-primary': '#8d4f00',
                secondary: '#cec5ba',
                'on-secondary': '#353028',
                'secondary-container': '#4c463d',
                'on-secondary-container': '#bdb4a9',
                tertiary: '#e2c0ab',
                'on-tertiary': '#412c1d',
                'tertiary-container': '#b0917e',
                'on-tertiary-container': '#402b1c',
                error: '#ffb4ab',
                'on-error': '#690005',
                'error-container': '#93000a',
                'on-error-container': '#ffdad6',
                'primary-fixed': '#ffdcc0',
                'primary-fixed-dim': '#ffb876',
                'on-primary-fixed': '#2d1600',
                'on-primary-fixed-variant': '#6b3b00',
                'secondary-fixed': '#ebe1d5',
                'secondary-fixed-dim': '#cec5ba',
                'on-secondary-fixed': '#1f1b14',
                'on-secondary-fixed-variant': '#4c463d',
                'tertiary-fixed': '#ffdcc6',
                'tertiary-fixed-dim': '#e2c0ab',
                'on-tertiary-fixed': '#2a170a',
                'on-tertiary-fixed-variant': '#5a4232',
                background: '#18120e',
                'on-background': '#ede0d9',
                'surface-variant': '#3b332f',
            },
        },
    },

    plugins: [forms],
};
